arb-dir: lib/l10n
template-arb-file: app_en.arb
arb-translate-api-key: AIzaSyBgIz4BuUWrOfDcXD2izQozNtxAKKnLQjw
arb-translate-context: gym app
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslatedShit.txt