// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBadGilmfdH9EeLATkW6_H_EIL9SyCg8o',
    appId: '1:904615135999:web:194c26efce4fb616135aca',
    messagingSenderId: '904615135999',
    projectId: 'app-chiqui',
    authDomain: 'app-chiqui.firebaseapp.com',
    storageBucket: 'app-chiqui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByf3vPUBA12qH0b2EcOBoWumhmAXq_4vA',
    appId: '1:904615135999:android:43967bf332b378d7135aca',
    messagingSenderId: '904615135999',
    projectId: 'app-chiqui',
    storageBucket: 'app-chiqui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPSvGpSaMAyf8HeVf2FuDBzVsYPN97c8',
    appId: '1:904615135999:ios:10940a2aed43b13d135aca',
    messagingSenderId: '904615135999',
    projectId: 'app-chiqui',
    storageBucket: 'app-chiqui.appspot.com',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPSvGpSaMAyf8HeVf2FuDBzVsYPN97c8',
    appId: '1:904615135999:ios:e5e6d1deb13a17d5135aca',
    messagingSenderId: '904615135999',
    projectId: 'app-chiqui',
    storageBucket: 'app-chiqui.appspot.com',
    iosBundleId: 'com.example.gymapp.RunnerTests',
  );
}
