// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIlDWDKtFsKC96nCrAb4mCHbbWib1aW70',
    appId: '1:347973756253:web:bb97a09fe715e42bf0f4b4',
    messagingSenderId: '347973756253',
    projectId: 'better-training-6a48a',
    authDomain: 'better-training-6a48a.firebaseapp.com',
    storageBucket: 'better-training-6a48a.appspot.com',
    measurementId: 'G-4XL1TEB4XJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZw5LV0qF4mCc7vvtpKbVssbUBngscahY',
    appId: '1:347973756253:android:95842691578261b4f0f4b4',
    messagingSenderId: '347973756253',
    projectId: 'better-training-6a48a',
    storageBucket: 'better-training-6a48a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSfmjBle9uvyiTa1anGVvRv2dlbNGUjSM',
    appId: '1:347973756253:ios:524177d9b3c188fcf0f4b4',
    messagingSenderId: '347973756253',
    projectId: 'better-training-6a48a',
    storageBucket: 'better-training-6a48a.appspot.com',
    iosBundleId: 'com.example.bettertraining',
  );
}
