import 'package:flutter/material.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

Map<String, String> getErrorCodes(BuildContext context) {
  final appLocalizations = AppLocalizations.of(context)!;
  return {
    "adminrestrictedoperation": appLocalizations.adminrestrictedoperation,
    "appnotauthorized": appLocalizations.appnotauthorized,
    "appnotinstalled": appLocalizations.appnotinstalled,
    "captchacheckfailed": appLocalizations.captchacheckfailed,
    "codeexpired": appLocalizations.codeexpired,
    "cordovanotready": appLocalizations.cordovanotready,
    "corsunsupported": appLocalizations.corsunsupported,
    "credentialalreadyinuse": appLocalizations.credentialalreadyinuse,
    "customtokenmismatch": appLocalizations.customtokenmismatch,
    "requiresrecentlogin": appLocalizations.requiresrecentlogin,
    "dynamiclinknotactivated": appLocalizations.dynamiclinknotactivated,
    "emailchangeneedsverification":
        appLocalizations.emailchangeneedsverification,
    "emailalreadyinuse": appLocalizations.emailalreadyinuse,
    "expiredactioncode": appLocalizations.expiredactioncode,
    "cancelledpopuprequest": appLocalizations.cancelledpopuprequest,
    "internalerror": appLocalizations.internalerror,
    "invalidappcredential": appLocalizations.invalidappcredential,
    "invalidappid": appLocalizations.invalidappid,
    "invalidusertoken": appLocalizations.invalidusertoken,
    "invalidauthevent": appLocalizations.invalidauthevent,
    "invalidverificationcode": appLocalizations.invalidverificationcode,
    "invalidcontinueuri": appLocalizations.invalidcontinueuri,
    "invalidcordovaconfiguration": appLocalizations.invalidcordovaconfiguration,
    "invalidcustomtoken": appLocalizations.invalidcustomtoken,
    "invaliddynamiclinkdomain": appLocalizations.invaliddynamiclinkdomain,
    "invalidemail": appLocalizations.invalidemail,
    "invalidapikey": appLocalizations.invalidapikey,
    "invalidcerthash": appLocalizations.invalidcerthash,
    "invalidcredential": appLocalizations.invalidcredential,
    "invalidmessagepayload": appLocalizations.invalidmessagepayload,
    "invalidmultifactorsession": appLocalizations.invalidmultifactorsession,
    "invalidoauthprovider": appLocalizations.invalidoauthprovider,
    "invalidoauthclientid": appLocalizations.invalidoauthclientid,
    "unauthorizeddomain": appLocalizations.unauthorizeddomain,
    "invalidactioncode": appLocalizations.invalidactioncode,
    "wrongpassword": appLocalizations.wrongpassword,
    "invalidpersistencetype": appLocalizations.invalidpersistencetype,
    "invalidphonenumber": appLocalizations.invalidphonenumber,
    "invalidproviderid": appLocalizations.invalidproviderid,
    "invalidrecipientemail": appLocalizations.invalidrecipientemail,
    "invalidsender": appLocalizations.invalidsender,
    "invalidverificationid": appLocalizations.invalidverificationid,
    "invalidtenantid": appLocalizations.invalidtenantid,
    "multifactorinfonotfound": appLocalizations.multifactorinfonotfound,
    "multifactorauthrequired": appLocalizations.multifactorauthrequired,
    "missingandroidpkgname": appLocalizations.missingandroidpkgname,
    "authdomainconfigrequired": appLocalizations.authdomainconfigrequired,
    "missingappcredential": appLocalizations.missingappcredential,
    "missingverificationcode": appLocalizations.missingverificationcode,
    "missingcontinueuri": appLocalizations.missingcontinueuri,
    "missingiframestart": appLocalizations.missingiframestart,
    "missingiosbundleid": appLocalizations.missingiosbundleid,
    "missingmultifactorinfo": appLocalizations.missingmultifactorinfo,
    "missingmultifactorsession": appLocalizations.missingmultifactorsession,
    "missingorinvalidnonce": appLocalizations.missingorinvalidnonce,
    "missingphonenumber": appLocalizations.missingphonenumber,
    "missingverificationid": appLocalizations.missingverificationid,
    "appdeleted": appLocalizations.appdeleted,
    "accountexistswithdifferentcredential":
        appLocalizations.accountexistswithdifferentcredential,
    "networkrequestfailed": appLocalizations.networkrequestfailed,
    "noauthevent": appLocalizations.noauthevent,
    "nosuchprovider": appLocalizations.nosuchprovider,
    "nulluser": appLocalizations.nulluser,
    "operationnotallowed": appLocalizations.operationnotallowed,
    "operationnotsupportedinthisenvironment":
        appLocalizations.operationnotsupportedinthisenvironment,
    "popupblocked": appLocalizations.popupblocked,
    "popupclosedbyuser": appLocalizations.popupclosedbyuser,
    "provideralreadylinked": appLocalizations.provideralreadylinked,
    "quotaexceeded": appLocalizations.quotaexceeded,
    "redirectcancelledbyuser": appLocalizations.redirectcancelledbyuser,
    "redirectoperationpending": appLocalizations.redirectoperationpending,
    "rejectedcredential": appLocalizations.rejectedcredential,
    "secondfactoralreadyinuse": appLocalizations.secondfactoralreadyinuse,
    "maximumsecondfactorcountexceeded":
        appLocalizations.maximumsecondfactorcountexceeded,
    "tenantidmismatch": appLocalizations.tenantidmismatch,
    "timeout": appLocalizations.timeout,
    "usertokenexpired": appLocalizations.usertokenexpired,
    "toomanyrequests": appLocalizations.toomanyrequests,
    "unauthorizedcontinueuri": appLocalizations.unauthorizedcontinueuri,
    "unsupportedfirstfactor": appLocalizations.unsupportedfirstfactor,
    "unsupportedpersistencetype": appLocalizations.unsupportedpersistencetype,
    "unsupportedtenantoperation": appLocalizations.unsupportedtenantoperation,
    "unverifiedemail": appLocalizations.unverifiedemail,
    "usercancelled": appLocalizations.usercancelled,
    "usernotfound": appLocalizations.usernotfound,
    "userdisabled": appLocalizations.userdisabled,
    "usermismatch": appLocalizations.usermismatch,
    "usersignedout": appLocalizations.usersignedout,
    "weakpassword": appLocalizations.weakpassword,
    "webstorageunsupported": appLocalizations.webstorageunsupported,
  };
}
